# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  version.MajorMinor: '1.0' # Manually adjusted
  version.Patch: $[counter(variables['version.MajorMinor'],0)]
  versionNumber: '$(version.MajorMinor).$(version.Patch)'
  prereleaseVersionNumber: 'Set dynamically below in a task'

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
              $majorVersion = '1'
              $minorVersion = '0'
              # Get the current datetime
              $dateTime = Get-Date -Format "yyyyMMdd-HHmmss"
              $buildId = $(Build.BuildId)
              $versionNumber = "$majorVersion.$minorVersion.$buildId.$dateTime"
              echo "##vso[task.setvariable variable=Version_Number]$versionNumber"
              displayName: 'Set Version Number'

